### ISSUE TITLE
tsdproxy 502 error

### ISSUE THREAD

**Issue by Tom7320** [almeidapaulopt/tsdproxy#54]
Hi everyone

Since the update to version 1 yesterday, tsdproxy stopped working for me. I try to access a website like nginx-test.funny-name.ts.net and get the following error message:

```
1:04PM ERR error host=nginx-test.funny-name.ts.net method=GET module=proxymanager proxyname=nginx-test status=502 url=/
2024/11/28 13:04:43 http: proxy error: dial tcp 172.29.0.2:80: i/o timeout
2024/11/28 13:04:46 http: proxy error: context canceled
```

Docker compose files:

```
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    container_name: tsdproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/tsdproxy:/data
    restart: unless-stopped
    environment:
      - TSDPROXY_AUTHKEY=tskey-auth-abc
      - TSDPROXY_HOSTNAME=192.168.205.2
      - DOCKER_HOST=unix:///var/run/docker.sock
```

```
services:
  web:
    image: nginx
    container_name: nginx-test
    ports:
      - "8080:80"
    labels:
      tsdproxy.enable: "true"
      tsdproxy.funnel: "true"
```

I really apologize for the perhaps stupid question, but it just stopped working for me since version 1, and I can not figure out why.... 

Thx for reading and the very useful project!

**Comment by SnowSquire** [comment]
i am getting the same issue

**Comment by almeidapaulopt** [comment]
can you try with the new version (v1.0.0-rc2) and send the logs

**Comment by Tom7320** [comment]
Still does not work for me. How do I enable verbose logging? `TSDPROXY_LOG_LEVEL=debug` did not do the trick. May I mail the log file to you? I don't want to post the entire log here....

**Comment by Tom7320** [comment]
It still does not work for me. Still 502 error:

```
Initializing server
Version 
loading configuration from: /config/tsdproxy.yaml
Validating configuration...
Setting up logger
4:46PM INF Log Settings Log level=debug
4:46PM INF Starting server Version=
4:46PM INF Setting up proxy proxies
4:46PM DBG Setting up Tailscale Providers module=proxymanager
4:46PM DBG Created Proxy provider module=proxymanager provider=default
4:46PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager
4:46PM DBG Creating proxies for provider module=proxymanager provider=local
4:46PM INF Trying to auto detect target URL container=/nginx-test docker=local module=proxymanager try=0
4:46PM DBG trying to connect to internal port container=/nginx-test docker=local hostname=192.168.205.2 module=proxymanager port=80
4:46PM INF Successfully connected address=172.28.0.2 container=/nginx-test docker=local module=proxymanager port=80
4:46PM DBG Creating proxy module=proxymanager proxy=nginx-test
4:46PM INF setting up proxy hostname=nginx-test module=proxymanager
4:46PM DBG initializing proxy hostname=nginx-test module=proxymanager proxyURL=https://nginx-test targetURL=http://172.28.0.2:80
4:46PM DBG Setting up tailscale server ephemeral=true hostname=nginx-test module=proxymanager runWebClient=false tailscale=default
4:46PM DBG Proxy server created successfully hostname=nginx-test module=proxymanager proxyname=nginx-test
4:46PM INF starting proxy module=proxymanager name=nginx-test proxyname=nginx-test
4:46PM INF Initializing WebServer
4:46PM INF Health check set to ready
4:46PM INF tsnet running state path /data/default/nginx-test/tailscaled.state module=proxymanager tailscale=default
4:46PM INF tsnet starting with hostname "nginx-test", varRoot "/data/default/nginx-test" module=proxymanager tailscale=default
4:46PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default
4:46PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default
4:47PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
4:47PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
4:48PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
2024/11/30 16:48:45 http: proxy error: context canceled
4:48PM ERR error host=nginx-test.owl-lionfish.ts.net method=GET module=proxymanager proxyname=nginx-test status=502 url=/
4:48PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
2024/11/30 16:49:15 http: proxy error: dial tcp 172.28.0.2:80: i/o timeout
4:49PM ERR error host=nginx-test.owl-lionfish.ts.net method=GET module=proxymanager proxyname=nginx-test status=502 url=/
4:49PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
4:49PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

I must admit, that I do not really understand the content of `tsdproxy.yaml`.

**Comment by mbadros** [comment]
I'm getting the same sort of problem.

If it helps ... 
```
   
Initializing server

Version 

loading configuration from: /config/tsdproxy.yaml

Validating configuration...

Setting up logger

11:07PM INF Log Settings Log level=info

11:07PM INF Starting server Version=

11:07PM INF Setting up proxy proxies

11:07PM INF Default Network found defaultIPAdress=172.17.0.1 docker=local module=proxymanager

11:07PM INF Trying to auto detect target URL container=/portainer-portainer-1 docker=local module=proxymanager try=0

11:07PM INF Trying to auto detect target URL container=/stirling-pdf docker=local module=proxymanager try=0

11:07PM INF Trying to auto detect target URL container=/airsonic-advanced docker=local module=proxymanager try=0

11:07PM INF Trying to auto detect target URL container=/freshrss docker=local module=proxymanager try=0

11:07PM INF Trying to auto detect target URL container=/calibre-web-automated docker=local module=proxymanager try=0

11:07PM INF Successfully connected address=192.168.144.2 container=/portainer-portainer-1 docker=local module=proxymanager port=9000

11:07PM INF Successfully connected address=172.20.0.2 container=/airsonic-advanced docker=local module=proxymanager port=4040

11:07PM INF Successfully connected address=192.168.128.2 container=/calibre-web-automated docker=local module=proxymanager port=8083

11:07PM INF Successfully connected address=172.23.0.2 container=/stirling-pdf docker=local module=proxymanager port=8080

11:07PM INF Trying to auto detect target URL container=/freshrss docker=local module=proxymanager try=1

11:07PM INF Trying to auto detect target URL container=/freshrss docker=local module=proxymanager try=2

11:08PM INF Trying to auto detect target URL container=/freshrss docker=local module=proxymanager try=3

11:08PM INF Trying to auto detect target URL container=/freshrss docker=local module=proxymanager try=4

11:08PM ERR error initializing proxy for container error="error getting proxy config: error parsing target hostname: no valid target found for /freshrss" docker=local module=proxymanager

11:08PM INF setting up proxy hostname=airsonic module=proxymanager

11:08PM INF setting up proxy hostname=pdf module=proxymanager

11:08PM INF Initializing WebServer

11:08PM INF setting up proxy hostname=cwa module=proxymanager

11:08PM INF starting proxy module=proxymanager name=pdf proxyname=pdf

11:08PM INF Health check set to ready

11:08PM INF starting proxy module=proxymanager name=airsonic proxyname=airsonic

11:08PM INF setting up proxy hostname=portainer module=proxymanager

11:08PM INF starting proxy module=proxymanager name=cwa proxyname=cwa

11:08PM INF starting proxy module=proxymanager name=portainer proxyname=portainer

11:08PM INF tsnet running state path /data/default/pdf/tailscaled.state module=proxymanager tailscale=default

11:08PM INF tsnet starting with hostname "pdf", varRoot "/data/default/pdf" module=proxymanager tailscale=default

11:08PM INF tsnet running state path /data/default/cwa/tailscaled.state module=proxymanager tailscale=default

11:08PM INF tsnet starting with hostname "cwa", varRoot "/data/default/cwa" module=proxymanager tailscale=default

11:08PM INF tsnet running state path /data/default/airsonic/tailscaled.state module=proxymanager tailscale=default

11:08PM INF tsnet running state path /data/default/portainer/tailscaled.state module=proxymanager tailscale=default

11:08PM INF tsnet starting with hostname "airsonic", varRoot "/data/default/airsonic" module=proxymanager tailscale=default

11:08PM INF tsnet starting with hostname "portainer", varRoot "/data/default/portainer" module=proxymanager tailscale=default

11:08PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default

11:08PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default

11:08PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default

11:08PM INF LocalBackend state is NeedsLogin; running StartLoginInteractive... module=proxymanager tailscale=default

11:09PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default

11:09PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default

11:09PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default

11:09PM INF AuthLoop: state is Running; done module=proxymanager tailscale=default

11:09PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

11:09PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

11:10PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

11:10PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

2024/11/30 23:10:33 http: TLS handshake error from 100.71.240.74:44320: write tcp 100.105.138.40:443->100.71.240.74:44320: i/o timeout

11:11PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

2024/11/30 23:11:03 http: proxy error: dial tcp 192.168.128.2:8083: i/o timeout

11:11PM ERR error host=cwa.hedgehog-vector.ts.net method=GET module=proxymanager proxyname=cwa status=502 url=/

11:11PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

11:12PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/

11:12PM INF request host=127.0.0.1:8080 method=GET status=200 url=/health/ready/
```

**Comment by pdg1** [comment]
I was getting the same issue.
I was able to get something working by adding my tsdproxy container to the same network as the containers i was trying to reach.

I'm still getting some 502 and 401 errors (see below)

`5:49AM ERR error host=dashy.ratfish-spica.ts.net method=GET module=proxymanager proxyname=dashy status=502 url=/css/chunk-1421ee6e.7601575f.css
2024/12/01 05:49:31 http: proxy error: context canceled
5:49AM ERR error host=dashy.ratfish-spica.ts.net method=GET module=proxymanager proxyname=dashy status=502 url=/css/chunk-0eec46d7.90cf07cd.css`

**Comment by SnowSquire** [comment]
can confim this bug was fixed, i deleted the tsdproxy_data volume before trying out the new version. thank you for fixing this

**Comment by Tom7320** [comment]
Yes. Same here. Thx for fixing! :-)

**Comment by lssong99** [comment]
Still not working for me.... v 1.4.3 I did deleted tsdproxy_data volume before proceed.

ERR error host=searxng-1.tail9924e6.ts.net method=GET module=proxymanager proxyname=myservice status=502 url=/
http: proxy error: dial tcp 172.31.0.1:38088: connect: connection refused

---- compose.yaml-------
services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - /home/docker-config/tsdproxy:/config
    restart: unless-stopped
    ports:
      - "58080:8080"

volumes:
  datadir:

------ tsdproxy.yaml ------
defaultproxyprovider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        defaultproxyprovider: default

tailscale:
    providers:
        default:
            authkey: tskey-auth-mykey
            controlurl: https://controlplane.tailscale.com
    datadir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false

**Comment by barrancoguy** [comment]
Hi, Anyone got to fix these ?

**Comment by ysautter** [comment]
I am experiencing the very same issue in v2

**Comment by cirrusflyer** [comment]
I'm testing in version 2 and also getting this.
